// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWDi9Gb-0G4oLMQ_X_4Cc2-J9lduxzLDA',
    appId: '1:254651161752:web:be5ee73d2bc73d404044ed',
    messagingSenderId: '254651161752',
    projectId: 'platform-2d-315d1',
    authDomain: 'platform-2d-315d1.firebaseapp.com',
    storageBucket: 'platform-2d-315d1.firebasestorage.app',
    measurementId: 'G-P8F9NZEDYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD77f6scjdbCL8Mbel9JofYTQZfjpVbMJU',
    appId: '1:254651161752:android:0fcc6ceab246d04e4044ed',
    messagingSenderId: '254651161752',
    projectId: 'platform-2d-315d1',
    storageBucket: 'platform-2d-315d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjbGBAUpEQAIaR92pxBtPKIrCVdqVVmgM',
    appId: '1:254651161752:ios:1da5389389f0b2824044ed',
    messagingSenderId: '254651161752',
    projectId: 'platform-2d-315d1',
    storageBucket: 'platform-2d-315d1.firebasestorage.app',
    iosBundleId: 'com.example.platformer2d',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWDi9Gb-0G4oLMQ_X_4Cc2-J9lduxzLDA',
    appId: '1:254651161752:web:25eb0b27f5250fcb4044ed',
    messagingSenderId: '254651161752',
    projectId: 'platform-2d-315d1',
    authDomain: 'platform-2d-315d1.firebaseapp.com',
    storageBucket: 'platform-2d-315d1.firebasestorage.app',
    measurementId: 'G-1JQS46N18J',
  );
}
